version: '1'
services:

  db_postgres:
    image: postgres:14
    container_name: postgres_todo
    restart: always
    ports:
        - "5432:5432"
    environment:
        POSTGRES_USER: "db_user"
        POSTGRES_PASSWORD: "db_pass"
        POSTGRES_DB: "todo_db"